# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
