# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
