# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import haha_api.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haha_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('choice_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('is_right', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('exam_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('room_id', models.CharField(db_index=True, default=haha_api.models._generate_random_room, max_length=64)),
                ('current_question_id', models.CharField(blank=True, max_length=64)),
                ('pub_date', models.DateTimeField()),
                ('state', models.CharField(default='draft', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haha_api.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('question_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('question_text', models.TextField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haha_api.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('vote_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haha_api.Choice')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haha_api.Exam')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haha_api.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haha_api.Question'),
        ),
    ]
