# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haha_api', '0002_auto_20180115_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='current_question_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
