# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haha_api', '0003_exam_current_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='state',
            field=models.CharField(default='draft', max_length=64),
        ),
    ]
